# 4-frontend-deployment.yaml
# Contains all Kubernetes resources for the React frontend application.

# --- Frontend Deployment ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: iira
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      # This section tells the pod how to authenticate with your private registry.
      imagePullSecrets:
      - name: regcred
      containers:
      - name: frontend
        # --- MODIFICATION: Updated image path to include your private registry ---
        image: registry.example.com:5000/iira/iira-frontend:1.0
        # --- END MODIFICATION ---
        ports:
        - containerPort: 80

---
# --- Frontend Service ---
# Exposes the frontend to the outside world.
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: iira
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      # The NodePort makes the service accessible from outside the cluster
      # on a specific port on the VM's IP address.
      nodePort: 30000 # You will access the app at http://<vm_ip>:30000
  type: NodePort

